version: '3'

services:
  myapp:
    build: .
    container_name: app_cont
    restart: always
    ports:
      - "8000:8000"  

    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium_container
    ports:
      - "4444:4444"  